<!-- SSG & Pre-Rendering — from ssg.md -->

<section class="hero-section">
  <span class="badge" t="docs.ssg.hero.badge"></span>
  <h1 class="hero-title" t="docs.ssg.hero.title"></h1>
  <p class="hero-subtitle" t="docs.ssg.hero.subtitle"></p>
</section>

<div class="doc-content">

  <!-- The Core Idea -->
  <div class="doc-section">
    <h2 class="doc-title" t="docs.ssg.coreIdea.title"></h2>
    <p class="doc-text" t="docs.ssg.coreIdea.text"></p>
    <div class="code-block"><pre><span class="hl-cmt">&lt;!-- HTML generated by your SSG / server with inline data --&gt;</span>
<span class="hl-tag">&lt;div</span> <span class="hl-attr">id</span>=<span class="hl-str">"app"</span> <span class="hl-attr">state</span>=<span class="hl-str">'{"product": {"name": "Sneaker X", "price": 299, "slug": "sneaker-x"}}'</span><span class="hl-tag">&gt;</span>
  <span class="hl-tag">&lt;h1</span> <span class="hl-attr">bind</span>=<span class="hl-str">"product.name"</span><span class="hl-tag">&gt;&lt;/h1&gt;</span>          <span class="hl-cmt">&lt;!-- "Sneaker X" — in initial HTML --&gt;</span>
  <span class="hl-tag">&lt;span</span> <span class="hl-attr">bind</span>=<span class="hl-str">"'$' + product.price"</span><span class="hl-tag">&gt;&lt;/span&gt;</span> <span class="hl-cmt">&lt;!-- "$299" — in initial HTML --&gt;</span>
<span class="hl-tag">&lt;/div&gt;</span></pre></div>
    <p class="doc-text" t="docs.ssg.coreIdea.text2"></p>
  </div>

  <!-- Patterns -->
  <div class="doc-section">
    <h2 class="doc-title" t="docs.ssg.patterns.title"></h2>

    <!-- Static pages (SSG) -->
    <h3 class="doc-subtitle" t="docs.ssg.patterns.staticTitle"></h3>
    <p class="doc-text" t="docs.ssg.patterns.staticText"></p>
    <p class="doc-text" t="docs.ssg.patterns.staticEleventyLabel"></p>
    <div class="code-block"><pre><span class="hl-cmt">---</span>
<span class="hl-cmt">layout: base.html</span>
<span class="hl-cmt">---</span>
<span class="hl-tag">&lt;div</span> <span class="hl-attr">id</span>=<span class="hl-str">"app"</span> <span class="hl-attr">state</span>=<span class="hl-str">'{{ product | dump }}'</span><span class="hl-tag">&gt;</span>
  <span class="hl-tag">&lt;h1</span> <span class="hl-attr">bind</span>=<span class="hl-str">"product.name"</span><span class="hl-tag">&gt;&lt;/h1&gt;</span>
  <span class="hl-tag">&lt;p</span> <span class="hl-attr">bind</span>=<span class="hl-str">"product.description"</span><span class="hl-tag">&gt;&lt;/p&gt;</span>
  <span class="hl-tag">&lt;button</span> <span class="hl-attr">post</span>=<span class="hl-str">"/api/cart/add"</span> <span class="hl-attr">body</span>=<span class="hl-str">'{"id":"{{ product.id }}"}'</span><span class="hl-tag">&gt;</span>
    Add to cart
  <span class="hl-tag">&lt;/button&gt;</span>
<span class="hl-tag">&lt;/div&gt;</span></pre></div>
    <div class="callout"><p t="docs.ssg.patterns.staticCallout"></p></div>
    <p class="doc-text" t="docs.ssg.patterns.staticText2"></p>

    <!-- Server-side rendering (SSR) -->
    <h3 class="doc-subtitle" t="docs.ssg.patterns.ssrTitle"></h3>
    <p class="doc-text" t="docs.ssg.patterns.ssrText"></p>
    <div class="code-block"><pre>app.<span class="hl-fn">get</span>(<span class="hl-str">'/products/:id'</span>, <span class="hl-kw">async</span> (<span class="hl-attr">req</span>, <span class="hl-attr">res</span>) <span class="hl-op">=&gt;</span> {
  <span class="hl-kw">const</span> product <span class="hl-op">=</span> <span class="hl-kw">await</span> db.products.<span class="hl-fn">findById</span>(req.params.id);
  res.<span class="hl-fn">render</span>(<span class="hl-str">'product'</span>, {
    <span class="hl-attr">state</span>: JSON.<span class="hl-fn">stringify</span>({ product })
  });
});</pre></div>
    <div class="code-block"><pre><span class="hl-cmt">&lt;!-- product.html template --&gt;</span>
<span class="hl-tag">&lt;div</span> <span class="hl-attr">id</span>=<span class="hl-str">"app"</span> <span class="hl-attr">state</span>=<span class="hl-str">"&lt;%= state %&gt;"</span><span class="hl-tag">&gt;</span>
  <span class="hl-tag">&lt;h1</span> <span class="hl-attr">bind</span>=<span class="hl-str">"product.name"</span><span class="hl-tag">&gt;&lt;/h1&gt;</span>
<span class="hl-tag">&lt;/div&gt;</span></pre></div>

    <!-- Hybrid: static structure, dynamic interaction -->
    <h3 class="doc-subtitle" t="docs.ssg.patterns.hybridTitle"></h3>
    <p class="doc-text" t="docs.ssg.patterns.hybridText"></p>
    <div class="code-block"><pre><span class="hl-cmt">&lt;!-- Pre-rendered initial state for Googlebot --&gt;</span>
<span class="hl-tag">&lt;div</span> <span class="hl-attr">id</span>=<span class="hl-str">"app"</span> <span class="hl-attr">state</span>=<span class="hl-str">'{"product": {"name": "Sneaker X", "stock": 12}}'</span><span class="hl-tag">&gt;</span>
  <span class="hl-tag">&lt;h1</span> <span class="hl-attr">bind</span>=<span class="hl-str">"product.name"</span><span class="hl-tag">&gt;&lt;/h1&gt;</span>
  <span class="hl-tag">&lt;span</span> <span class="hl-attr">bind</span>=<span class="hl-str">"product.stock + ' in stock'"</span><span class="hl-tag">&gt;&lt;/span&gt;</span>

  <span class="hl-cmt">&lt;!-- Dynamic: only runs after user interaction, not needed for SEO --&gt;</span>
  <span class="hl-tag">&lt;button</span> <span class="hl-attr">post</span>=<span class="hl-str">"/api/cart/add"</span> <span class="hl-attr">body</span>=<span class="hl-str">'{"id":"sneaker-x"}'</span> <span class="hl-attr">then</span>=<span class="hl-str">"cart.count++"</span><span class="hl-tag">&gt;</span>
    Add to cart
  <span class="hl-tag">&lt;/button&gt;</span>
<span class="hl-tag">&lt;/div&gt;</span></pre></div>
  </div>

  <!-- What to put in state= vs get= -->
  <div class="doc-section">
    <h2 class="doc-title" t="docs.ssg.stateVsGet.title"></h2>
    <table class="doc-table">
      <thead>
        <tr><th t="docs.ssg.stateVsGet.colContentType"></th><th t="docs.ssg.stateVsGet.colApproach"></th><th t="docs.ssg.stateVsGet.colWhy"></th></tr>
      </thead>
      <tbody>
        <tr><td t="docs.ssg.stateVsGet.row1Col1"></td><td t="docs.ssg.stateVsGet.row1Col2"></td><td t="docs.ssg.stateVsGet.row1Col3"></td></tr>
        <tr><td t="docs.ssg.stateVsGet.row2Col1"></td><td t="docs.ssg.stateVsGet.row2Col2"></td><td t="docs.ssg.stateVsGet.row2Col3"></td></tr>
        <tr><td t="docs.ssg.stateVsGet.row3Col1"></td><td t="docs.ssg.stateVsGet.row3Col2"></td><td t="docs.ssg.stateVsGet.row3Col3"></td></tr>
        <tr><td t="docs.ssg.stateVsGet.row4Col1"></td><td t="docs.ssg.stateVsGet.row4Col2"></td><td t="docs.ssg.stateVsGet.row4Col3"></td></tr>
      </tbody>
    </table>
  </div>

  <!-- Rule of Thumb -->
  <div class="doc-section">
    <h2 class="doc-title" t="docs.ssg.ruleOfThumb.title"></h2>
    <div class="code-block"><pre><span class="hl-cmt">Content a search engine should index  → put it in state= (pre-rendered)</span>
<span class="hl-cmt">Content that changes per user/session  → use get= (fetched client-side)</span></pre></div>
    <p class="doc-text" t="docs.ssg.ruleOfThumb.text"></p>
  </div>

  <!-- No.JS + Eleventy Quick-Start -->
  <div class="doc-section">
    <h2 class="doc-title" t="docs.ssg.eleventyQuickStart.title"></h2>
    <div class="code-block"><pre>npm install @11ty/eleventy</pre></div>
    <div class="code-block"><pre><span class="hl-cmt">_site/           &larr; built HTML output (deploy this)</span>
<span class="hl-cmt">_includes/</span>
<span class="hl-cmt">  base.html      &larr; base layout</span>
<span class="hl-cmt">pages/</span>
<span class="hl-cmt">  product.njk    &larr; product page template</span>
<span class="hl-cmt">_data/</span>
<span class="hl-cmt">  products.json  &larr; your data</span>
<span class="hl-cmt">.eleventy.js</span></pre></div>

    <h3 class="doc-subtitle" t="docs.ssg.eleventyQuickStart.configTitle"></h3>
    <div class="code-block"><pre>module.exports <span class="hl-op">=</span> <span class="hl-kw">function</span>(<span class="hl-attr">eleventyConfig</span>) {
  eleventyConfig.<span class="hl-fn">addPassthroughCopy</span>(<span class="hl-str">"assets"</span>);
  <span class="hl-kw">return</span> { <span class="hl-attr">dir</span>: { <span class="hl-attr">output</span>: <span class="hl-str">"_site"</span> } };
};</pre></div>

    <h3 class="doc-subtitle" t="docs.ssg.eleventyQuickStart.productTemplateTitle"></h3>
    <div class="code-block"><pre><span class="hl-cmt">---</span>
<span class="hl-cmt">layout: base.html</span>
<span class="hl-cmt">pagination:</span>
<span class="hl-cmt">  data: products</span>
<span class="hl-cmt">  size: 1</span>
<span class="hl-cmt">  alias: product</span>
<span class="hl-cmt">permalink: /products/{{ product.slug }}/</span>
<span class="hl-cmt">---</span>
<span class="hl-tag">&lt;div</span> <span class="hl-attr">id</span>=<span class="hl-str">"app"</span> <span class="hl-attr">state</span>=<span class="hl-str">'{{ product | dump }}'</span><span class="hl-tag">&gt;</span>
  <span class="hl-tag">&lt;h1</span> <span class="hl-attr">bind</span>=<span class="hl-str">"product.name"</span><span class="hl-tag">&gt;&lt;/h1&gt;</span>
  <span class="hl-tag">&lt;p</span> <span class="hl-attr">bind</span>=<span class="hl-str">"product.description"</span><span class="hl-tag">&gt;&lt;/p&gt;</span>
<span class="hl-tag">&lt;/div&gt;</span></pre></div>

    <h3 class="doc-subtitle" t="docs.ssg.eleventyQuickStart.baseLayoutTitle"></h3>
    <div class="code-block"><pre><span class="hl-tag">&lt;!DOCTYPE html&gt;</span>
<span class="hl-tag">&lt;html&gt;</span>
<span class="hl-tag">&lt;head&gt;</span>
  <span class="hl-tag">&lt;title&gt;</span>{{ product.name }} | My Store<span class="hl-tag">&lt;/title&gt;</span>
  <span class="hl-tag">&lt;meta</span> <span class="hl-attr">name</span>=<span class="hl-str">"description"</span> <span class="hl-attr">content</span>=<span class="hl-str">"{{ product.description }}"</span><span class="hl-tag">&gt;</span>
  <span class="hl-tag">&lt;script</span> <span class="hl-attr">src</span>=<span class="hl-str">"/assets/no.js"</span> <span class="hl-attr">defer</span><span class="hl-tag">&gt;&lt;/script&gt;</span>
<span class="hl-tag">&lt;/head&gt;</span>
<span class="hl-tag">&lt;body&gt;</span>{{ content | safe }}<span class="hl-tag">&lt;/body&gt;</span>
<span class="hl-tag">&lt;/html&gt;</span></pre></div>
    <p class="doc-text" t="docs.ssg.eleventyQuickStart.text"></p>
  </div>

  <!-- Security Note -->
  <div class="doc-section">
    <h2 class="doc-title" t="docs.ssg.securityNote.title"></h2>
    <p class="doc-text" t="docs.ssg.securityNote.text"></p>
    <div class="code-block"><pre><span class="hl-cmt">// Node.js — safe embedding</span>
<span class="hl-kw">const</span> stateJson <span class="hl-op">=</span> JSON.<span class="hl-fn">stringify</span>(product).<span class="hl-fn">replace</span>(<span class="hl-str">/&lt;/g</span>, <span class="hl-str">'\\u003c'</span>).<span class="hl-fn">replace</span>(<span class="hl-str">/&gt;/g</span>, <span class="hl-str">'\\u003e'</span>);
<span class="hl-cmt">// &rarr; use stateJson as the state= attribute value</span></pre></div>
    <p class="doc-text" t="docs.ssg.securityNote.text2"></p>
  </div>

  <!-- Managing <head> in SSG Pages -->
  <div class="doc-section">
    <h2 class="doc-title" t="docs.ssg.managingHead.title"></h2>
    <p class="doc-text" t="docs.ssg.managingHead.text1"></p>
    <p class="doc-text" t="docs.ssg.managingHead.text2"></p>
    <p class="doc-text" t="docs.ssg.managingHead.text3"></p>
  </div>

</div>
